name: nested_navigation_gorouter_example
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.4+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: 8.0.3
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.5.4
  google_fonts:
  fl_chart: ^0.55.1
  flutter_riverpod: ^1.0.4
  logger: ^1.1.0
  auto_size_text: ^3.0.0
  intl_phone_field: ^3.1.0
  pin_code_fields:
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.5
  expandable: ^5.0.1
  table_calendar: ^3.0.7
  flutter_staggered_grid_view: ^0.7.0
  intl:
  hive: ^2.2.3
  shimmer: ^2.0.0
  flutter_expandable_fab: ^1.6.0
  stop_watch_timer:
  syncfusion_flutter_datepicker: ^20.2.50
  awesome_dialog: ^3.0.2
  package_info_plus:
  flutter_secure_storage: ^9.0.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  device_info_plus: ^10.0.0
  firebase_messaging: ^14.6.9
  isar_flutter_libs: ^3.1.0+1
  isar: ^3.1.0+1
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.2.0
  flutter_polyline_points: ^1.0.0
  flutter_typeahead: 5.0.2
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.8.2
  url_launcher: ^6.2.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.18

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  # background_image: "assets/"
  image: assets/logos/play_store_512.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/google_sans/ProductSans-Regular.ttf
